name: update readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
  push:
    

jobs:
  update-readme:
    name: update readme
    runs-on: ubuntu-latest
    permissions: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4    
    
      - name: update wakatime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: '⣀⣄⣤⣦⣶⣷⣿'
          TIME_RANGE: 'all_time'
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          
      - name: generate contributions
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: update contributions
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Updated contribution image with new data"
