name: Wakatime

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
  push:
    

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: '⣀⣄⣤⣦⣶⣷⣿'
          TIME_RANGE: 'all_time'
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: snake.svg?palette=github-dark
